#!/usr/bin/env bash
trap 'rm -f ~/projects/Archipelago/output/apworlds/mathquest.apworld; exit 0' TERM
if test -n "$VERSION"; then
  sed -i 's/"world_version": .*,/"world_version": "'"$VERSION"'.0.0",/' archipelago.json
fi
python3.13 make_apworlds.py mathquest &>/dev/null
generate-global-tracker-data MathQuest &>/dev/null
echo ~/projects/Archipelago/output/apworlds/mathquest.apworld

while :; do
  sleep 1
done
